# Generated by Django 4.1.13 on 2026-05-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reject_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
